GET http://localhost:5267/games

###
http://localhost:5267/games/3

###
POST http://localhost:5267/games
Content-Type: application/json

{
    "Name": "test game",
    "GenreId": 1,
    "Price": 9.99,
    "releaseDate": "1991-02-01"
}

###
PUT http://localhost:5267/games/2
Content-Type: application/json

{
    "Name": "Street Fighter II Turbo",
    "GenreId": 1,
    "Price": 19.99,
    "releaseDate": "1991-02-01"
}

###
DELETE http://localhost:5267/games/3